#!/bin/bash
function killservice()
{   
    pgrep -x $1 > /dev/null 
    if [ $? -eq 0 ]
    then
        killall -9 -q $1 & > /dev/null
    fi
}
killservice 'psme-rest-server';
killservice 'psme-chassis';

sudo ldconfig
