#!/bin/sh
#################################################################################
# Support Platform  type
#################################################################################
# Define currnt using variable depend on platform #

	#CURRENT_FAN_NODE_PATH="/sys/devices/platform/as7816_64x_fan/"
	CURRENT_FAN_NODE_PATH="/sys/bus/i2c/devices/17-0068/"
	CURRENT_PSU1_FAN_NODE_PATH="/sys/bus/i2c/devices/9-0058/"
	CURRENT_PSU2_FAN_NODE_PATH="/sys/bus/i2c/devices/10-005b/"

	eval CURRENT_THERMAL_NODE1_PATH="/sys/devices/platform/coretemp.0/hwmon/hwmon0/temp2_input"
	eval CURRENT_THERMAL_NODE2_PATH="/sys/bus/i2c/devices/18-0048/hwmon/hwmon6/temp1_input"
	eval CURRENT_THERMAL_NODE3_PATH="/sys/bus/i2c/devices/18-0049/hwmon/hwmon7/temp1_input"
	eval CURRENT_THERMAL_NODE4_PATH="/sys/bus/i2c/devices/18-004a/hwmon/hwmon8/temp1_input"
	eval CURRENT_THERMAL_NODE5_PATH="/sys/bus/i2c/devices/18-004b/hwmon/hwmon9/temp1_input"
	eval CURRENT_THERMAL_NODE6_PATH="/sys/bus/i2c/devices/17-004d/hwmon/hwmon10/temp1_input"
	eval CURRENT_THERMAL_NODE7_PATH="/sys/bus/i2c/devices/17-004e/hwmon/hwmon11/temp1_input"
	eval CURRENT_THERMAL_NODE8_PATH="/sys/bus/i2c/devices/9-0058/psu_temp1_input"
	eval CURRENT_THERMAL_NODE9_PATH="/sys/bus/i2c/devices/10-005b/psu_temp1_input"
	CURRENT_THERMAL_NUM="9"
	CURRENT_PORT_NUM="64"
        CURRENT_PSU_NUM="2"	

	I2C_BUS="0"
	I2C_CPLD_OFFSET="0"
	SYSTEM_RESET_OFFSET="0"

	SYSTEM_HALT_VALUE="0"
	SYSTEM_RESTART_VALUE="0"

	mapping=("XSFP" "XSFP" "XSFP" "XSFP" "XSFP" "XSFP" "XSFP" "XSFP" "XSFP" "XSFP"
	         "XSFP" "XSFP" "XSFP" "XSFP" "XSFP" "XSFP" "XSFP" "XSFP" "XSFP" "XSFP"
	         "XSFP" "XSFP" "XSFP" "XSFP" "XSFP" "XSFP" "XSFP" "XSFP" "XSFP" "XSFP"
	         "XSFP" "XSFP" "XSFP" "XSFP" "XSFP" "XSFP" "XSFP" "XSFP" "XSFP" "XSFP"
	         "XSFP" "XSFP" "XSFP" "XSFP" "XSFP" "XSFP" "XSFP" "XSFP" "XSFP" "XSFP"
	         "XSFP" "XSFP" "XSFP" "XSFP" "XSFP" "XSFP" "XSFP" "XSFP" "XSFP" "XSFP"
	         "XSFP" "XSFP" "XSFP" "XSFP" )

        fans_type=("S" "S" "S" "S" "P" "P")

        thermals_type=("C" "S" "S" "S" "S" "S" "S" "P" "P")

        psus_type=("S" "S")
	

get_sfp_port_path()
{
	if [ "${1}" -ge 1 -a "${1}" -le "${CURRENT_PORT_NUM}" ] ; then
			spath=${mapping[${1}]}
			eval CURRENT_SFP_PORT_PATH="/sys/bus/i2c/devices/${spath}"
			echo "${CURRENT_SFP_PORT_PATH}"
	else
		echo "error port number"
	fi
}

