#!/bin/bash
function killservice()
{   
    pgrep -x $1 > /dev/null 
    if [ $? -eq 0 ]
    then
        killall -9 -q $1 & > /dev/null
    fi
}

killservice 'Restd';
killservice 'IPMIModule';
killservice 'Memdbd';
killservice 'Assetd';
killservice 'AssetModule'
killservice 'Redfishd';
killservice 'RMMLogd';
killservice 'Registerd';
# dont kill ONL snmpd killservice 'snmpd';
killservice 'SNMPSubagentd';

sudo ldconfig

#chown -R root /root/.ssh
#chgrp -R root /root/.ssh
